# Generated by Django 5.2.3 on 2025-07-04 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0003_remove_producto_cliente'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detallesventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente'),
        ),
    ]
