# Generated by Django 5.2.3 on 2025-07-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_activo'),
        ('ventas', '0003_alter_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto'),
        ),
    ]
