# Generated by Django 5.2.3 on 2025-07-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cliente',
        ),
    ]
